// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Or0OpVHB5TS834nKvj_aOofs682RCa8',
    appId: '1:810028557423:web:62e5e5285ee5d89a15d99a',
    messagingSenderId: '810028557423',
    projectId: 'helping-hands-4318b',
    authDomain: 'helping-hands-4318b.firebaseapp.com',
    storageBucket: 'helping-hands-4318b.appspot.com',
    measurementId: 'G-9LHH1PPX1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA35bjCHh0af3tCgpe3CWFpWSvrIvwIkg4',
    appId: '1:810028557423:android:727c51d9f2ab828815d99a',
    messagingSenderId: '810028557423',
    projectId: 'helping-hands-4318b',
    storageBucket: 'helping-hands-4318b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKLpEAxbYSwrN8JfweS-WjP2CAAoYEmk',
    appId: '1:810028557423:ios:18373a8727e42f6015d99a',
    messagingSenderId: '810028557423',
    projectId: 'helping-hands-4318b',
    storageBucket: 'helping-hands-4318b.appspot.com',
    androidClientId: '810028557423-huh2673brllmuhnj85p4kelf2of6itl7.apps.googleusercontent.com',
    iosClientId: '810028557423-lkqm51jds5tkmbq74mm30tsg1khtgvdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpingHands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmKLpEAxbYSwrN8JfweS-WjP2CAAoYEmk',
    appId: '1:810028557423:ios:18373a8727e42f6015d99a',
    messagingSenderId: '810028557423',
    projectId: 'helping-hands-4318b',
    storageBucket: 'helping-hands-4318b.appspot.com',
    androidClientId: '810028557423-huh2673brllmuhnj85p4kelf2of6itl7.apps.googleusercontent.com',
    iosClientId: '810028557423-lkqm51jds5tkmbq74mm30tsg1khtgvdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpingHands',
  );
}
